# Generated by Django 5.2.13 on 2026-08-04 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary',
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Hyderabad', 'Hyderabad'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Sialkot', 'Sialkot'), ('Gujranwala', 'Gujranwala'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cnic_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format XXXXX-XXXXXXX-X.', regex='^\\d{5}-\\d{7}-\\d$')], verbose_name='CNIC Number'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='raw_skills_text',
            field=models.TextField(blank=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume (PDF)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ntn_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='NTN Number'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Hyderabad', 'Hyderabad'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Sialkot', 'Sialkot'), ('Gujranwala', 'Gujranwala'), ('Other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_max_pkr',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximum Salary (PKR)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_min_pkr',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum Salary (PKR)'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +92XXXXXXXXXX.', regex='^\\+92\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-match_score'], name='app_match_score_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active', '-created_at'], name='job_active_created_idx'),
        ),
    ]
