# Generated by Django 5.2.13 on 2026-08-04 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_pkr', models.PositiveIntegerField(default=0, verbose_name='Price (PKR)')),
                ('max_jobs', models.PositiveIntegerField(default=5, verbose_name='Max Active Jobs')),
                ('has_featured_badge', models.BooleanField(default=False, verbose_name='Featured Badge')),
                ('has_cpp_matching_priority', models.BooleanField(default=False, verbose_name='C++ Matching Priority')),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
            },
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='job_type',
            new_name='workplace_type',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='workplace_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=10, verbose_name='Workplace Type'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Review', 'In Review'), ('Shortlist', 'Shortlisted'), ('Interview', 'Interview'), ('Rejected', 'Rejected')], db_index=True, default='Submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Professional Title'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium (Gold Badge)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website URL'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Key Requirements'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Peshawar', 'Peshawar'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Quetta', 'Quetta'), ('Sialkot', 'Sialkot'), ('Remote', 'Remote Pakistan')], db_index=True, default='Lahore', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_pdf',
            field=models.FileField(null=True, upload_to='resumes/', verbose_name='Resume (PDF)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(verbose_name='Company Description'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='ntn_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='NTN Number'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='city',
            field=models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Peshawar', 'Peshawar'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Quetta', 'Quetta'), ('Sialkot', 'Sialkot'), ('Remote', 'Remote Pakistan')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.companyprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+92XXXXXXXXXX'.", regex='^\\+92[0-9]{10}$')]),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.subscriptiontier', verbose_name='Subscription Tier'),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='core.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.jobposting')),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-saved_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
